### ISSUE TITLE
init-tls-secret image exec /bin/sh: exec format error

### ISSUE THREAD

**Issue by e3b0c442** [jp-gouin/helm-openldap#119]
**Describe the bug**
`init-tls-secret` image does not appear to be multi-arch by default.

**To Reproduce**
1. Attempt helm install on an arm64 cluster

**Expected behavior**
Helm chart installs without issue

**Screenshots**

**Additional context**

The default image appears to be alpine/openssl, which not only is not multiarch, but has not been built in more than 3 years.

If you need a prebuilt container with openssl installed, the docker nginx container is relatively small, is multiarch, has openssl, and is updated frequently.

Alternatively I'd be happy to submit a PR that uses GitHub actions to regularly build a multi-arch alpine-based openssl container and stores it in GitHub container registry.

**Comment by jp-gouin** [comment]
Yeah I know , I noticed it when I implemented the feature that's why you can configure this under `customTls.image.repository` 
I was a bit lazy 😁

Feel free to maybe create a repo with what you suggest , if you don't want to own it you can transfer the ownership to me.

I think it best to separate the container creation from this chart and have them into separate repo
