### ISSUE TITLE
FR: ldapDomain no longer applicable with bitnami

### ISSUE THREAD

**Issue by EugenMayer** [jp-gouin/helm-openldap#204]
AFAIU / AFAICS ldapDomain is nothing that can be used with the bitnami chart. There is LDAP_ROOT, but this is a DN syntax

https://github.com/jp-gouin/helm-openldap/blob/master/values.yaml#L16

I assume `LDAP_ROOT` should no be set via 

```yaml
env:
   LDAP_ROOT: dc=example,dc=com
```

but ldapDomain is probably confusing people.

**Comment by EugenMayer** [comment]
I found were you use the domain: https://github.com/jp-gouin/helm-openldap/blob/master/templates/statefulset.yaml#L113 so its for the SSL certificate, if you generate one. Maybe we should then document this and distinguish it from LDAP_ROOT?

I think this is esp. problematic/configusing for people joining over from osixia since  ldap_domain was used for both there AFAIR

**Comment by EugenMayer** [comment]
I have found https://github.com/jp-gouin/helm-openldap/blob/master/templates/configmap-env.yaml#L20, but baseDomain is not part of https://github.com/jp-gouin/helm-openldap/blob/master/values.yaml at all. 

Maybe we just add `baseDomain` above ldapDomain and explain what is what?

**Comment by jp-gouin** [comment]
Hi @EugenMayer , LDAP ROOT is now configured using `global.ldapDomain` , more detail [here](https://github.com/jp-gouin/helm-openldap?tab=readme-ov-file#global-section)  which is more friendly user than an env variable

**Comment by jp-gouin** [comment]
Yes only if you bring your own certificate using `initTLSSecret.secret`

**Comment by EugenMayer** [comment]
I will use a own certificate anyway, it must be officially signed anyhow. 

Thanks for clarifying!

**Comment by EugenMayer** [comment]
it seems like due to https://github.com/jp-gouin/helm-openldap/blob/7e1aa76ed81cf8758bbbe4a5ae73c126203c1b9d/templates/_helpers.tpl#L245

gloabl.baseDomain is always overridden by ldapDomain, even if one has set `global.baseDomain` in the values.yaml

So as far as i can see, there is no way to let the cert generate for `external.ldap-mycompany.tld` while the ldap base dn is `dc=mycompany,dc=com`

For me personally, the external domain does have nothing to do with the actual ldap root and should be freely configureable.

I can fix it for me by either:

1. overriding LDAP_ROOT in the env section
2. just provide a own certificate and thus set `ldapDomain` to whatever i need as LDAP_ROOT and ignore the self signed  cert

1. works for all cases, 2. only if you do not care about the self signed certificate.

Is this how you designed it for simplicity reasons? If yes, i can see the appeal to just set the ldapDomain, but maybe let `global.baseDomain` from the `values.yaml` take precendence?

**Comment by jp-gouin** [comment]
`ldapDomain` is the top object of the ldap base . You can configure it explicitly `dc=toto,c=ca` or domain based `toto.ca`.
This value is used to generate the replication certificate , but since all replica end up with their own certs without SAN , the communication is encrypted but the certificate is not verified. 

It's also used to automatically configured `phpldapadmin` and `ltb-passwd` to work out of the box with your openldap base. 

If you want to have a certificate with `CN=external.ldap-mycompany.tld` then yes you have to use your own .

`global.baseDomain` is an internal variable always in the form of `aa=bb,cc=dd,...` and propagated everywhere in the chart and sub-chart and should not be configured directly (and I don't think it's possible but I never tried :) )

**Comment by EugenMayer** [comment]
I see, fair enough. Works for me, i understood your design / vision here
