### ISSUE TITLE
Any reason why LDAP_BASE_DN is not setable via ENV

### ISSUE THREAD

**Issue by EugenMayer** [jp-gouin/helm-openldap#53]
For me it was convinient to set the `LDAP_BASE_DN` via the ENV file, since the image supports it ( see https://github.com/EugenMayer/docker-rancher-extra-catalogs/blob/master/templates/openldap/26/docker-compose.yml#L14 )

Are there any particular reasons you do not support setting this out of the box, are there technical issues you are trying to avoid? 

Great to have your insight / design decision here, thanks!

**Comment by jp-gouin** [comment]
Hi @EugenMayer 

The chart is currenlty under a large refractoring to match best practices and be more user friendly to use.
You can track/contribute under the branch https://github.com/jp-gouin/helm-openldap/tree/refractor-chart.

I hope to get some time soon to finish the work

**Comment by jp-gouin** [comment]
Hi @EugenMayer ,
You probably figure something else by the time but I’d still want to answer your question ☺️
from the osixia openldap documentation 
LDAP_DOMAIN: Ldap domain. Defaults to example.org
LDAP_BASE_DN: Ldap base DN. If empty automatically set from LDAP_DOMAIN value. Defaults to (empty)

Both are possible but it’s true that I choose the LDAP_DOMAIN approach , a little bit more natural but that just my opinion.
It will be complicated now that I’ve done the refactoring to use LDAP_BASE_DN because I use LDAP_DOMAIN variable in the helper to unit global variable used by sub charts .
